# Docker config to build a new InaSAFE package each night
nginx:
  image: nginx
  volumes:
    - ./build:/usr/share/nginx/html:ro
  ports:
    - "8998:80"
  restart: on-failure:5

cron:
  build: .
  volumes:
    - ./build:/build
    # To ensure date / time / tz synced with host
    - /etc/localtime:/etc/localtime:ro
  restart: on-failure:5

